package terraform

import (
	"fmt"
	"strings"

	"github.com/matthewdriscoll/infraplane/internal/domain"
)

// providerBlocks maps cloud providers to their Terraform provider configuration.
var providerBlocks = map[domain.CloudProvider]string{
	domain.ProviderAWS: `terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}`,
	domain.ProviderGCP: `terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = "my-project"
  region  = "us-central1"
}`,
}

// GenerateConfig assembles a complete Terraform configuration for an application
// on a given provider by combining the provider block with per-resource HCL.
func GenerateConfig(app domain.Application, resources []domain.Resource, provider domain.CloudProvider) (string, error) {
	block, ok := providerBlocks[provider]
	if !ok {
		return "", fmt.Errorf("unsupported provider: %s", provider)
	}

	var sb strings.Builder

	// Header comment
	sb.WriteString(fmt.Sprintf("# Terraform configuration for %s on %s\n", app.Name, provider))
	sb.WriteString(fmt.Sprintf("# Generated by Infraplane\n\n"))

	// Provider block
	sb.WriteString(block)
	sb.WriteString("\n\n")

	// Resource blocks from each resource's provider mapping
	resourceCount := 0
	for _, r := range resources {
		mapping, ok := r.ProviderMappings[provider]
		if !ok {
			continue
		}
		if mapping.TerraformHCL == "" {
			continue
		}

		sb.WriteString(fmt.Sprintf("# %s: %s (%s → %s)\n", r.Kind, r.Name, r.Kind, mapping.ServiceName))
		sb.WriteString(mapping.TerraformHCL)
		sb.WriteString("\n\n")
		resourceCount++
	}

	if resourceCount == 0 {
		sb.WriteString("# No resources with Terraform mappings for this provider.\n")
	}

	return sb.String(), nil
}

// GenerateResourceHCL returns just the Terraform HCL for a single resource
// on the given provider. Returns empty string if no mapping exists.
func GenerateResourceHCL(resource domain.Resource, provider domain.CloudProvider) string {
	mapping, ok := resource.ProviderMappings[provider]
	if !ok {
		return ""
	}
	return mapping.TerraformHCL
}
