package terraform

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/matthewdriscoll/infraplane/internal/domain"
)

// blockHeaderPattern matches the start of top-level HCL blocks:
//   variable "name" {
//   resource "type" "name" {
//   output "name" {
//   data "type" "name" {
//   locals {
var blockHeaderPattern = regexp.MustCompile(`^(variable|resource|output|data|locals)\s+("([^"]+)"\s*("([^"]+)")?\s*)?{`)

// GenerateProviderBlock builds the terraform + provider blocks dynamically
// based on the cloud provider and an optional deploy target.
func GenerateProviderBlock(provider domain.CloudProvider, target *domain.DeployTarget) string {
	switch provider {
	case domain.ProviderAWS:
		return generateAWSProviderBlock(target)
	case domain.ProviderGCP:
		return generateGCPProviderBlock(target)
	default:
		return fmt.Sprintf("# Unsupported provider: %s\n", provider)
	}
}

func generateAWSProviderBlock(target *domain.DeployTarget) string {
	region := "us-east-1"
	if target != nil && target.AWSRegion != "" {
		region = target.AWSRegion
	}

	var sb strings.Builder
	sb.WriteString(`terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
`)
	sb.WriteString(fmt.Sprintf("  region = %q\n", region))

	if target != nil && target.AWSRoleARN != "" {
		sb.WriteString("\n  assume_role {\n")
		sb.WriteString(fmt.Sprintf("    role_arn = %q\n", target.AWSRoleARN))
		sb.WriteString("  }\n")
	}

	sb.WriteString("}")
	return sb.String()
}

func generateGCPProviderBlock(target *domain.DeployTarget) string {
	project := "my-project"
	region := "us-central1"
	if target != nil {
		if target.GCPProjectID != "" {
			project = target.GCPProjectID
		}
		if target.GCPRegion != "" {
			region = target.GCPRegion
		}
	}

	return fmt.Sprintf(`terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = %q
  region  = %q
}`, project, region)
}

// GenerateConfig assembles a complete Terraform configuration for an application
// on a given provider by combining the provider block with per-resource HCL.
func GenerateConfig(app domain.Application, resources []domain.Resource, provider domain.CloudProvider, target *domain.DeployTarget) (string, error) {
	block := GenerateProviderBlock(provider, target)

	var sb strings.Builder

	// Header comment
	sb.WriteString(fmt.Sprintf("# Terraform configuration for %s on %s\n", app.Name, provider))
	sb.WriteString(fmt.Sprintf("# Generated by Infraplane\n\n"))

	// Provider block
	sb.WriteString(block)
	sb.WriteString("\n\n")

	// Resource blocks from each resource's provider mapping
	resourceCount := 0
	for _, r := range resources {
		mapping, ok := r.ProviderMappings[provider]
		if !ok {
			continue
		}
		if mapping.TerraformHCL == "" {
			continue
		}

		sb.WriteString(fmt.Sprintf("# %s: %s (%s → %s)\n", r.Kind, r.Name, r.Kind, mapping.ServiceName))
		sb.WriteString(mapping.TerraformHCL)
		sb.WriteString("\n\n")
		resourceCount++
	}

	if resourceCount == 0 {
		sb.WriteString("# No resources with Terraform mappings for this provider.\n")
	}

	// Deduplicate variables, outputs, and shared resources that appear in
	// multiple per-resource HCL blocks (e.g. variable "project_id", VPC, subnet).
	return deduplicateHCL(sb.String()), nil
}

// GenerateResourceHCL returns just the Terraform HCL for a single resource
// on the given provider. Returns empty string if no mapping exists.
func GenerateResourceHCL(resource domain.Resource, provider domain.CloudProvider) string {
	mapping, ok := resource.ProviderMappings[provider]
	if !ok {
		return ""
	}
	return mapping.TerraformHCL
}

// deduplicateHCL removes duplicate top-level HCL blocks from a combined
// Terraform configuration. When multiple resources are generated independently,
// each may include its own variable, output, or shared infrastructure blocks.
// This function keeps only the first occurrence of each unique block.
func deduplicateHCL(hcl string) string {
	lines := strings.Split(hcl, "\n")
	seen := make(map[string]bool)
	var result []string
	i := 0

	for i < len(lines) {
		line := lines[i]
		trimmed := strings.TrimSpace(line)

		// Check if this line starts a top-level HCL block
		matches := blockHeaderPattern.FindStringSubmatch(trimmed)
		if matches == nil {
			// Not a block header — keep the line as-is
			result = append(result, line)
			i++
			continue
		}

		// Build a signature for this block to detect duplicates
		// matches[1] = block type (variable, resource, output, data, locals)
		// matches[3] = first quoted name (e.g. "project_id" for variable, "google_compute_network" for resource)
		// matches[5] = second quoted name (e.g. "vpc" for resource "google_compute_network" "vpc")
		blockType := matches[1]
		sig := blockType
		if matches[3] != "" {
			sig += ":" + matches[3]
		}
		if matches[5] != "" {
			sig += ":" + matches[5]
		}

		// Find the end of this block by tracking brace depth
		blockStart := i
		depth := 0
		for i < len(lines) {
			for _, ch := range lines[i] {
				if ch == '{' {
					depth++
				} else if ch == '}' {
					depth--
				}
			}
			i++
			if depth == 0 {
				break
			}
		}

		if seen[sig] {
			// Skip this duplicate block (and any trailing blank line)
			if i < len(lines) && strings.TrimSpace(lines[i]) == "" {
				i++
			}
			continue
		}

		seen[sig] = true
		// Keep the block
		result = append(result, lines[blockStart:i]...)
	}

	return strings.Join(result, "\n")
}
