package terraform

import (
	"fmt"
	"strings"

	"github.com/matthewdriscoll/infraplane/internal/domain"
)

// GenerateProviderBlock builds the terraform + provider blocks dynamically
// based on the cloud provider and an optional deploy target.
func GenerateProviderBlock(provider domain.CloudProvider, target *domain.DeployTarget) string {
	switch provider {
	case domain.ProviderAWS:
		return generateAWSProviderBlock(target)
	case domain.ProviderGCP:
		return generateGCPProviderBlock(target)
	default:
		return fmt.Sprintf("# Unsupported provider: %s\n", provider)
	}
}

func generateAWSProviderBlock(target *domain.DeployTarget) string {
	region := "us-east-1"
	if target != nil && target.AWSRegion != "" {
		region = target.AWSRegion
	}

	var sb strings.Builder
	sb.WriteString(`terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
`)
	sb.WriteString(fmt.Sprintf("  region = %q\n", region))

	if target != nil && target.AWSRoleARN != "" {
		sb.WriteString("\n  assume_role {\n")
		sb.WriteString(fmt.Sprintf("    role_arn = %q\n", target.AWSRoleARN))
		sb.WriteString("  }\n")
	}

	sb.WriteString("}")
	return sb.String()
}

func generateGCPProviderBlock(target *domain.DeployTarget) string {
	project := "my-project"
	region := "us-central1"
	if target != nil {
		if target.GCPProjectID != "" {
			project = target.GCPProjectID
		}
		if target.GCPRegion != "" {
			region = target.GCPRegion
		}
	}

	return fmt.Sprintf(`terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

provider "google" {
  project = %q
  region  = %q
}`, project, region)
}

// GenerateConfig assembles a complete Terraform configuration for an application
// on a given provider by combining the provider block with per-resource HCL.
func GenerateConfig(app domain.Application, resources []domain.Resource, provider domain.CloudProvider, target *domain.DeployTarget) (string, error) {
	block := GenerateProviderBlock(provider, target)

	var sb strings.Builder

	// Header comment
	sb.WriteString(fmt.Sprintf("# Terraform configuration for %s on %s\n", app.Name, provider))
	sb.WriteString(fmt.Sprintf("# Generated by Infraplane\n\n"))

	// Provider block
	sb.WriteString(block)
	sb.WriteString("\n\n")

	// Resource blocks from each resource's provider mapping
	resourceCount := 0
	for _, r := range resources {
		mapping, ok := r.ProviderMappings[provider]
		if !ok {
			continue
		}
		if mapping.TerraformHCL == "" {
			continue
		}

		sb.WriteString(fmt.Sprintf("# %s: %s (%s → %s)\n", r.Kind, r.Name, r.Kind, mapping.ServiceName))
		sb.WriteString(mapping.TerraformHCL)
		sb.WriteString("\n\n")
		resourceCount++
	}

	if resourceCount == 0 {
		sb.WriteString("# No resources with Terraform mappings for this provider.\n")
	}

	return sb.String(), nil
}

// GenerateResourceHCL returns just the Terraform HCL for a single resource
// on the given provider. Returns empty string if no mapping exists.
func GenerateResourceHCL(resource domain.Resource, provider domain.CloudProvider) string {
	mapping, ok := resource.ProviderMappings[provider]
	if !ok {
		return ""
	}
	return mapping.TerraformHCL
}
